[project]
name = "finance-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=1.0.1",
    "langgraph>=1.0.8",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
]
